server:
  port: 5001
  servlet:
    context-path: /unit-test

spring:
  application:
    name: unit-test-demo
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml # log 文件位置
    drop-first: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/unit_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 12345678
